# Generated by Django 6.0.4 on 2026-04-12 13:15

from django.db import migrations, models

import mailing.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriberEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subscribed", models.BooleanField(default=None, null=True)),
                ("google_authenticated", models.BooleanField(default=False)),
                (
                    "token",
                    models.CharField(
                        default=mailing.models.generate_token,
                        max_length=24,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
