# Generated by Django 6.0.4 on 2026-05-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriberemail",
            name="custom_greeting",
            field=models.TextField(
                blank=True,
                help_text="A customized greeting for the megaphone. Used to add a personal note to friends.",
            ),
        ),
        migrations.AddField(
            model_name="subscriberemail",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
